language: python

sudo: required

matrix:
    include:
        - python: 2.7
          os: linux
          sudo: required
          services:
              - docker
          env:
              - DOCKER_IMG=cpascual/taurus-test:debian-jessie

        - python: 2.7
          os: linux
          sudo: required
          services:
              - docker
          env:
              - DOCKER_IMG=cpascual/taurus-test:debian-stretch

        - python: 2.7
          os: linux
          sudo: required
          services:
              - docker
          env:
              - DOCKER_IMG=cpascual/taurus-test:debian-buster

before_install:
  - docker run -d --name=taurus-test -h taurus-test --volume=`pwd`:/taurus $DOCKER_IMG
  - sleep 10
  
script:
  - docker exec taurus-test /bin/bash -c "cd taurus ; python setup.py install"
  - docker exec taurus-test /bin/bash -c "TAURUS_STARTER_WAIT=5 taurustestsuite -e 'taurus\.core\.util\.test\.test_timer'"
